version: '3'
services:
  spotisongs:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/src
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI
      - FLASK_SECRET
